/*
 * WizardDownloadHistoryProgressJPanel.java
 *
 * Created on June 16, 2007, 6:32 PM
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * Copyright (C) 2007 Cheok YanCheng <yccheok@yahoo.com>
 */

package org.yccheok.jstock.gui;

import javax.swing.*;
import java.awt.*;
import org.yccheok.jstock.engine.*;
        
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.yccheok.jstock.engine.*;
import org.yccheok.jstock.analysis.*;

/**
 *
 * @author  yccheok
 */
public class WizardDownloadHistoryProgressJPanel extends javax.swing.JPanel {
    
    /** Creates new form WizardDownloadHistoryProgressJPanel */
    public WizardDownloadHistoryProgressJPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jXHeader1 = new org.jdesktop.swingx.JXHeader();
        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jXHeader1.setDescription("The KLSE history is now being downloaded to your computer. This may take several minutes depending on the number of stocks which you had selected.");
        jXHeader1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/128x128/socket.png")));
        jXHeader1.setTitle("Downloading KLSE History");
        add(jXHeader1, java.awt.BorderLayout.NORTH);

        jProgressBar1.setStringPainted(true);

        jLabel1.setText("Downloading in progress. 0 out of 0 stock(s) completed");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        add(jPanel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    private class DownloadHistoryTask extends SwingWorker<java.util.Map<Code, java.util.List<OperatorIndicator>>, Integer> {
        private volatile boolean runnable = true;
        private java.util.List<Code> codes;
        private java.util.List<String> projects;
        
        public DownloadHistoryTask(java.util.List<String> projects, java.util.List<Code> codes) {
            this.projects = projects;
            this.codes = codes;            
        }
        
        public void _stop() {
            runnable = false;
        }
        
        public java.util.Map<Code, java.util.List<OperatorIndicator>> doInBackground() {
            final MainFrame m = (MainFrame)javax.swing.SwingUtilities.getAncestorOfClass(MainFrame.class, WizardDownloadHistoryProgressJPanel.this);
            final java.util.List<StockServerFactory> stockServerFactories = m.getStockServerFactory();
            final StockHistorySerializer stockHistorySerializer = m.getStockHistorySerializer();            
            final StockCodeAndSymbolDatabase stockCodeAndSymbolDatabase = m.getStockCodeAndSymbolDatabase();
            final IndicatorProjectManager indicatorProjectManager = m.getIndicatorProjectManager();            
            final java.util.Map<Code, java.util.List<OperatorIndicator>> operatorIndicators = new java.util.HashMap<Code, java.util.List<OperatorIndicator>>();
            
            for(Code code : codes) {
                operatorIndicators.put(code, new java.util.ArrayList<OperatorIndicator>());
            }
            
            int count = 0;
            
            publish(count);

            // First, check whether there is a need to get stock history.
            boolean isHistoryNeeded = false;
            for(String project : projects) {
                if(DownloadHistoryTask.this.isCancelled() || !DownloadHistoryTask.this.runnable) {
                    return null;
                }

                final OperatorIndicator operatorIndicator = indicatorProjectManager.getOperatorIndicator(project);
                
                if(operatorIndicator != null) {
                    if(operatorIndicator.isStockHistoryServerNeeded()) {
                        isHistoryNeeded = true;
                        break;
                    }
                }
            }
            
            for(final Code code : codes) {

                StockHistoryServer stockHistoryServer = null;

                if(isHistoryNeeded) {
                    for(StockServerFactory stockServerFactory : stockServerFactories) {
                        if(DownloadHistoryTask.this.isCancelled() || !DownloadHistoryTask.this.runnable) {
                            return null;
                        }

                        stockHistoryServer = stockServerFactory.getStockHistoryServer(code);                    

                        if(stockHistoryServer != null) {
                            /*
                            if(stockHistorySerializer.save(stockHistoryServer) == false)
                            {
                                log.error("Error in serializing stock code " + code);
                            } 
                            */
                            break;
                        }
                    }
                }
                
                java.util.List<OperatorIndicator> result = operatorIndicators.get(code);

                for(String project : projects) {
                    if(DownloadHistoryTask.this.isCancelled() || !DownloadHistoryTask.this.runnable) {
                        return null;
                    }

                    final OperatorIndicator operatorIndicator = indicatorProjectManager.getOperatorIndicator(project);

                    if(operatorIndicator != null) {
                        final Stock stock = Utils.getEmptyStock(code, stockCodeAndSymbolDatabase.codeToSymbol(code));                    

                        if(operatorIndicator.isStockHistoryServerNeeded()) {
                            if(stockHistoryServer != null)
                            {
                            	operatorIndicator.setStockHistoryServer(stockHistoryServer);
                            }
                            else
                            {
                                // We need history but we fail to get one. Skip this project.
                                continue;
                            }
                        }
                        
                        operatorIndicator.setStock(stock);

                        operatorIndicator.preCalculate();

                        result.add(operatorIndicator);
                    }                    
                }

                count++;
                publish(count);
                
            }   /* for(String code : codes) */
                        
            return operatorIndicators;
         }

         protected void process(java.util.List<Integer> progresses) {
             for (Integer progress : progresses) {
                 jProgressBar1.setValue(progress);
                 jLabel1.setForeground(Color.BLACK);
                 jLabel1.setText("Downloading in progress. " + progress + " out of " + codes.size() + " stock(s) completed");
             }
         }
         
        public void done() {            
            try {
                operatorIndicators = get();
            }
            catch(InterruptedException exp) {
                log.error("", exp);
            }
            catch(java.util.concurrent.ExecutionException exp) {
                log.error("", exp);
            }
            
            if(operatorIndicators != null)
            {
                jLabel1.setForeground(Color.BLUE);
                jLabel1.setText("Downloading completed with " + codes.size() + " stock(s)");
                propertyChangeSupport.firePropertyChange("downloading", false, true);
            }
            else
            {
                jLabel1.setForeground(Color.RED);
                jLabel1.setText("Downloading is not completed");
            }
        }
    }
    
    public void startDownload(java.util.List<String> projects, java.util.List<Code> codes) {
        if(downloadHistoryTask != null) {
            downloadHistoryTask._stop();
            try {
                downloadHistoryTask.get();
            }
            catch(InterruptedException exp) {
                log.error("", exp);
            }
            catch(java.util.concurrent.ExecutionException exp) {
                log.error("", exp);
            }
        }
        
        jProgressBar1.setMaximum(codes.size());
        
        downloadHistoryTask = new DownloadHistoryTask(projects, codes);
        downloadHistoryTask.execute();
    }
    
    public void stopDownload() {
        if(downloadHistoryTask != null) {
            downloadHistoryTask._stop();
            try {
                downloadHistoryTask.get();
            }
            catch(InterruptedException exp) {
                log.error("", exp);
            }
            catch(java.util.concurrent.ExecutionException exp) {
                log.error("", exp);
            }
        } 
        
        downloadHistoryTask = null;
    }
    
    public void addMyPropertyChangeListener(java.beans.PropertyChangeListener listener) 
    {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }
    
    // Code -> OperatorIndicator List
    public java.util.Map<Code, java.util.List<OperatorIndicator>> getOperatorIndicators() {
        return java.util.Collections.unmodifiableMap(operatorIndicators);
    }
    
    private static final Log log = LogFactory.getLog(WizardDownloadHistoryProgressJPanel.class);
    private DownloadHistoryTask downloadHistoryTask;
    private java.beans.PropertyChangeSupport propertyChangeSupport = new java.beans.PropertyChangeSupport(this);
    private java.util.Map<Code, java.util.List<OperatorIndicator>> operatorIndicators = new java.util.HashMap<Code, java.util.List<OperatorIndicator>>();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    // End of variables declaration//GEN-END:variables
    
}
