/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.yccheok.jstock.gui.portfolio;

import java.awt.Dimension;
import java.text.MessageFormat;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import org.yccheok.jstock.engine.Code;
import org.yccheok.jstock.engine.StockInfo;
import org.yccheok.jstock.engine.Symbol;
import org.yccheok.jstock.gui.JStock;
import org.yccheok.jstock.gui.PortfolioManagementJPanel;
import org.yccheok.jstock.gui.UIOptions;
import org.yccheok.jstock.internationalization.MessagesBundle;

/**
 *
 * @author yccheok
 */
public class RenameStockJDialog extends javax.swing.JDialog {

    private static class UppercaseDocumentFilter extends DocumentFilter {
        @Override
        public void insertString(DocumentFilter.FilterBypass fb, int offset,
                String text, AttributeSet attr) throws BadLocationException {

            fb.insertString(offset, text.toUpperCase(), attr);
        }

        @Override
        public void replace(DocumentFilter.FilterBypass fb, int offset, int length,
                String text, AttributeSet attrs) throws BadLocationException {

            fb.replace(offset, length, text.toUpperCase(), attrs);
        }
    }
    
    private class MyDocumentListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            updateOkButton();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            updateOkButton();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            updateOkButton();
        }        
    }
    
    /**
     * Creates new form RenameStockJDialog
     */
    public RenameStockJDialog(java.awt.Frame parent, boolean modal, StockInfo originalStockInfo, PortfolioManagementJPanel portfolioManagementJPanel) {
        super(parent, modal);
        
        this.originalStockInfo = originalStockInfo;
        this.portfolioManagementJPanel = portfolioManagementJPanel;

        initComponents();
               
        // Hackish way to make Mac works.
        pack();
        
        Dimension dimension = JStock.instance().getUIOptions().getDimension(UIOptions.RENAME_STOCK_JDIALOG);
        if (dimension != null) {
            setSize(dimension);
        }
        
        // Ensure all upper case.
        ((AbstractDocument) jTextField2.getDocument()).setDocumentFilter(new UppercaseDocumentFilter());
        
        // Listen for changes in the text.
        jTextField2.getDocument().addDocumentListener(documentListener);
        jTextField1.getDocument().addDocumentListener(documentListener);
        
        this.jTextField2.setText(originalStockInfo.code.toString());
        this.jTextField1.setText(originalStockInfo.symbol.toString());
        this.jTextField3.setText(originalStockInfo.code.toString());
        this.jTextField4.setText(originalStockInfo.symbol.toString());
        
        updateOkButton();
    }

    private String getNewCodeAsString() {
        final String newCode = this.jTextField2.getText().trim();
        return newCode;
    }

    private String getNewSymbolAsString() {
        final String newCode = this.jTextField1.getText().trim();
        return newCode;
    }
        
    private void updateOkButton() {
        final String newCodeAsString = getNewCodeAsString();
        final String newSymbolAsString = getNewSymbolAsString();
        
        // Empty input. Reject.
        if (newCodeAsString.isEmpty() || newSymbolAsString.isEmpty()) {
            jButton1.setEnabled(false);
            return;
        }
        
        if (!newCodeAsString.equalsIgnoreCase(originalStockInfo.code.toString())) {
            jButton1.setEnabled(true);
            return;
        }
        
        if (!newSymbolAsString.equals(originalStockInfo.symbol.toString())) {
            jButton1.setEnabled(true);
            return;
        }
        
        // No change. Reject.
        jButton1.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXHeader1 = new org.jdesktop.swingx.JXHeader();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/yccheok/jstock/data/gui"); // NOI18N
        setTitle(bundle.getString("RenameStockJDialog_Title")); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        jXHeader1.setDescription(bundle.getString("RenameStockJDialog_Description")); // NOI18N
        jXHeader1.setTitle(bundle.getString("RenameStockJDialog_Title")); // NOI18N
        getContentPane().add(jXHeader1, java.awt.BorderLayout.PAGE_START);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/16x16/apply.png"))); // NOI18N
        jButton1.setText(bundle.getString("RenameStockJDialog_OK")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/16x16/button_cancel.png"))); // NOI18N
        jButton2.setText(bundle.getString("RenameStockJDialog_Cancel")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        getContentPane().add(jPanel4, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("RenameStockJDialog_Original"))); // NOI18N

        jLabel3.setText(bundle.getString("RenameStockJDialog_OriginalCode")); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(76, 14));

        jLabel4.setText(bundle.getString("RenameStockJDialog_OriginalSymbol")); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(76, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(76, 14));
        jLabel4.setPreferredSize(new java.awt.Dimension(76, 14));

        jTextField3.setEditable(false);

        jTextField4.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jTextField3))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("RenameStockJDialog_New"))); // NOI18N

        jLabel1.setText(bundle.getString("RenameStockDialog_NewCode")); // NOI18N

        jLabel2.setText(bundle.getString("RenameStockJDialog_NewSymbol")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(76, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(76, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(76, 14));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 342, 330);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        JStock.instance().getUIOptions().setDimension(UIOptions.RENAME_STOCK_JDIALOG, getSize());
    }//GEN-LAST:event_formWindowClosed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        final String newCodeAsString = getNewCodeAsString();
        final String newSymbolAsString = getNewSymbolAsString();
        final String oldCodeAsString = originalStockInfo.code.toString();
        final String oldSymbolAsString = originalStockInfo.symbol.toString();
        
        if (!newCodeAsString.equals(oldCodeAsString)) {
            final String output = MessageFormat.format(MessagesBundle.getString("question_message_rename_code_template"), oldCodeAsString, newCodeAsString);
            final int result = javax.swing.JOptionPane.showConfirmDialog(JStock.instance(), output, MessagesBundle.getString("question_title_rename"), javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE);
            if (result != javax.swing.JOptionPane.YES_OPTION) {
                return;
            }
        }
        
        if (!newSymbolAsString.equals(oldSymbolAsString)) {
            final String output = MessageFormat.format(MessagesBundle.getString("question_message_rename_symbol_template"), oldSymbolAsString, newSymbolAsString);
            final int result = javax.swing.JOptionPane.showConfirmDialog(JStock.instance(), output, MessagesBundle.getString("question_title_rename"), javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE);
            if (result != javax.swing.JOptionPane.YES_OPTION) {
                return;
            }
        }
        
        final StockInfo newStockInfo = StockInfo.newInstance(Code.newInstance(newCodeAsString), Symbol.newInstance(newSymbolAsString));
        final StockInfo oldStockInfo = StockInfo.newInstance(Code.newInstance(oldCodeAsString), Symbol.newInstance(oldSymbolAsString));
        
        if (newStockInfo.equals(oldStockInfo)) {
            return;
        }
        
        if (!this.portfolioManagementJPanel.rename(newStockInfo, oldStockInfo)) {
            return;
        }
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private final StockInfo originalStockInfo;
    private final PortfolioManagementJPanel portfolioManagementJPanel;
    private final MyDocumentListener documentListener = new MyDocumentListener();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    // End of variables declaration//GEN-END:variables
}
