application: jstock-webapp
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /get-time\.py
  script: get-time.py
  
- url: /get-ip\.py
  script: get-ip.py
  
- url: /missing-stock-code/.*
  script: missing-stock-code.app
  secure: always  